/*
 * This file was automatically generated by EvoSuite
 * Sat May 24 18:13:03 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Solution3341;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Solution3341_ESTest extends Solution3341_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution3341 solution3341_0 = new Solution3341();
      int[][] intArray0 = new int[1][6];
      int[] intArray1 = new int[1];
      intArray0[0] = intArray1;
      int int0 = solution3341_0.minTimeToReach(intArray0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution3341 solution3341_0 = new Solution3341();
      int[][] intArray0 = new int[2][3];
      int[] intArray1 = new int[1];
      intArray1[0] = Integer.MAX_VALUE;
      intArray0[0] = intArray1;
      intArray0[1] = intArray1;
      int int0 = solution3341_0.minTimeToReach(intArray0);
      assertEquals(Integer.MIN_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution3341 solution3341_0 = new Solution3341();
      // Undeclared exception!
      try { 
        solution3341_0.minTimeToReach((int[][]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Solution3341", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution3341 solution3341_0 = new Solution3341();
      int[][] intArray0 = new int[6][0];
      // Undeclared exception!
      try { 
        solution3341_0.minTimeToReach(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("original.Solution3341", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Solution3341 solution3341_0 = new Solution3341();
      int[][] intArray0 = new int[8][5];
      int[] intArray1 = new int[5];
      intArray1[1] = Integer.MAX_VALUE;
      intArray1[2] = (-2545);
      intArray0[0] = intArray1;
      int[] intArray2 = new int[20];
      intArray2[0] = Integer.MAX_VALUE;
      intArray0[1] = intArray2;
      int int0 = solution3341_0.minTimeToReach(intArray0);
      assertEquals(9, int0);
  }
}
