/*
 * This file was automatically generated by EvoSuite
 * Sat May 24 19:50:51 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Solution0517;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Solution0517_ESTest extends Solution0517_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution0517 solution0517_0 = new Solution0517();
      int[] intArray0 = new int[7];
      intArray0[1] = 1262;
      int int0 = solution0517_0.findMinMoves(intArray0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution0517 solution0517_0 = new Solution0517();
      int[] intArray0 = new int[7];
      intArray0[0] = (-1);
      intArray0[1] = 1262;
      intArray0[2] = 765;
      intArray0[3] = 3702;
      intArray0[4] = 1;
      intArray0[5] = 851;
      int int0 = solution0517_0.findMinMoves(intArray0);
      assertEquals(2762, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution0517 solution0517_0 = new Solution0517();
      // Undeclared exception!
      try { 
        solution0517_0.findMinMoves((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Solution0517", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution0517 solution0517_0 = new Solution0517();
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        solution0517_0.findMinMoves(intArray0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("original.Solution0517", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Solution0517 solution0517_0 = new Solution0517();
      int[] intArray0 = new int[7];
      intArray0[0] = (-1);
      int int0 = solution0517_0.findMinMoves(intArray0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Solution0517 solution0517_0 = new Solution0517();
      int[] intArray0 = new int[2];
      int int0 = solution0517_0.findMinMoves(intArray0);
      assertEquals(0, int0);
  }
}
