/*
 * This file was automatically generated by EvoSuite
 * Thu May 29 02:06:29 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Solution2538;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Solution2538_ESTest extends Solution2538_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution2538 solution2538_0 = new Solution2538();
      int[][] intArray0 = new int[2][9];
      int[] intArray1 = new int[8];
      intArray1[0] = 1;
      intArray0[0] = intArray1;
      int[] intArray2 = new int[8];
      intArray2[1] = 1;
      long long0 = solution2538_0.maxOutput(57, intArray0, intArray2);
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution2538 solution2538_0 = new Solution2538();
      int[][] intArray0 = new int[9][6];
      long long0 = solution2538_0.maxOutput(1, intArray0, intArray0[4]);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution2538 solution2538_0 = new Solution2538();
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        solution2538_0.maxOutput(7, (int[][]) null, intArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Solution2538", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution2538 solution2538_0 = new Solution2538();
      int[][] intArray0 = new int[1][4];
      int[] intArray1 = new int[8];
      // Undeclared exception!
      try { 
        solution2538_0.maxOutput((-2644), intArray0, intArray1);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -2644
         //
         verifyException("original.Solution2538", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Solution2538 solution2538_0 = new Solution2538();
      int[][] intArray0 = new int[6][6];
      // Undeclared exception!
      try { 
        solution2538_0.maxOutput(0, intArray0, intArray0[4]);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("original.Solution2538", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Solution2538 solution2538_0 = new Solution2538();
      int[][] intArray0 = new int[2][9];
      int[] intArray1 = new int[8];
      intArray1[0] = 1;
      intArray0[0] = intArray1;
      long long0 = solution2538_0.maxOutput(57, intArray0, intArray1);
      assertEquals(3L, long0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Solution2538 solution2538_0 = new Solution2538();
      int[][] intArray0 = new int[56][6];
      // Undeclared exception!
      solution2538_0.maxOutput(79, intArray0, intArray0[4]);
  }
}
