/*
 * This file was automatically generated by EvoSuite
 * Thu May 29 01:38:06 GMT 2025
 */

package original;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import original.Solution1955;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Solution1955_ESTest extends Solution1955_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Solution1955 solution1955_0 = new Solution1955();
      int[] intArray0 = new int[7];
      intArray0[0] = 1947;
      int int0 = solution1955_0.countSpecialSubsequences(intArray0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Solution1955 solution1955_0 = new Solution1955();
      int[] intArray0 = new int[9];
      intArray0[4] = 1;
      intArray0[5] = (-293);
      int int0 = solution1955_0.countSpecialSubsequences(intArray0);
      assertEquals(15, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Solution1955 solution1955_0 = new Solution1955();
      // Undeclared exception!
      try { 
        solution1955_0.countSpecialSubsequences((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("original.Solution1955", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Solution1955 solution1955_0 = new Solution1955();
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        solution1955_0.countSpecialSubsequences(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("original.Solution1955", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Solution1955 solution1955_0 = new Solution1955();
      int[] intArray0 = new int[1];
      intArray0[0] = (-3258);
      int int0 = solution1955_0.countSpecialSubsequences(intArray0);
      assertEquals(0, int0);
  }
}
